#!/usr/bin/env python3

from graph import Graph
from evolutionary import evolutionary, evolutionary2, evolutionary3
    
GRAPH = Graph()
GRAPH2 = Graph()
GRAPH3 = Graph()
GRAPH4 = Graph()

GRAPH.add_vertex('A')
GRAPH.add_vertex('B')
GRAPH.add_vertex('C')
GRAPH.add_vertex('D')
GRAPH.add_vertex('E')

GRAPH.add_edge(('A', 'B'), 13)
GRAPH.add_edge(('B', 'C'), 30)
GRAPH.add_edge(('C', 'D'), 33)
GRAPH.add_edge(('D', 'A'), 66)
GRAPH.add_edge(('E', 'A'), 70)
GRAPH.add_edge(('E', 'B'), 55)
GRAPH.add_edge(('E', 'C'), 42)

GRAPH2.add_vertex('A')
GRAPH2.add_vertex('B')
GRAPH2.add_vertex('C')
GRAPH2.add_vertex('D')
GRAPH2.add_vertex('E')

GRAPH2.add_edge(('A', 'B'), 10)
GRAPH2.add_edge(('A', 'C'), 15)
GRAPH2.add_edge(('A', 'D'), 20)
GRAPH2.add_edge(('A', 'E'), 25)
GRAPH2.add_edge(('B', 'C'), 12)
GRAPH2.add_edge(('B', 'D'), 27)
GRAPH2.add_edge(('B', 'E'), 22)
GRAPH2.add_edge(('C', 'D'), 17)
GRAPH2.add_edge(('C', 'E'), 30)
GRAPH2.add_edge(('D', 'E'), 35)

GRAPH3.add_vertex('A')
GRAPH3.add_vertex('B')
GRAPH3.add_vertex('C')
GRAPH3.add_vertex('D')
GRAPH3.add_vertex('E')
GRAPH3.add_vertex('F')

GRAPH3.add_edge(('A', 'B'), 29)
GRAPH3.add_edge(('A', 'C'), 20)
GRAPH3.add_edge(('A', 'D'), 21)
GRAPH3.add_edge(('A', 'E'), 18)
GRAPH3.add_edge(('A', 'F'), 10)
GRAPH3.add_edge(('B', 'C'), 15)
GRAPH3.add_edge(('B', 'D'), 28)
GRAPH3.add_edge(('B', 'E'), 17)
GRAPH3.add_edge(('B', 'F'), 14)
GRAPH3.add_edge(('C', 'D'), 23)
GRAPH3.add_edge(('C', 'E'), 11)
GRAPH3.add_edge(('C', 'F'), 8)
GRAPH3.add_edge(('D', 'E'), 27)
GRAPH3.add_edge(('D', 'F'), 25)
GRAPH3.add_edge(('E', 'F'), 12)

GRAPH4.add_vertex('A')
GRAPH4.add_vertex('B')
GRAPH4.add_vertex('C')
GRAPH4.add_vertex('D')
GRAPH4.add_vertex('E')
GRAPH4.add_vertex('F')
GRAPH4.add_vertex('G')
GRAPH4.add_vertex('H')
GRAPH4.add_vertex('I')

GRAPH4.add_edge(('A', 'B'), 29)
GRAPH4.add_edge(('A', 'C'), 20)
GRAPH4.add_edge(('A', 'D'), 21)
GRAPH4.add_edge(('A', 'E'), 18)
GRAPH4.add_edge(('A', 'F'), 10)
GRAPH4.add_edge(('A', 'G'), 30)
GRAPH4.add_edge(('A', 'H'), 31)
GRAPH4.add_edge(('A', 'I'), 32)
GRAPH4.add_edge(('B', 'C'), 15)
GRAPH4.add_edge(('B', 'D'), 28)
GRAPH4.add_edge(('B', 'E'), 17)
GRAPH4.add_edge(('B', 'F'), 14)
GRAPH4.add_edge(('B', 'G'), 24)
GRAPH4.add_edge(('B', 'H'), 26)
GRAPH4.add_edge(('B', 'I'), 33)
GRAPH4.add_edge(('C', 'D'), 23)
GRAPH4.add_edge(('C', 'E'), 11)
GRAPH4.add_edge(('C', 'F'), 8)
GRAPH4.add_edge(('C', 'G'), 19)
GRAPH4.add_edge(('C', 'H'), 22)
GRAPH4.add_edge(('C', 'I'), 34)
GRAPH4.add_edge(('D', 'E'), 27)
GRAPH4.add_edge(('D', 'F'), 25)
GRAPH4.add_edge(('D', 'G'), 16)
GRAPH4.add_edge(('D', 'H'), 35)
GRAPH4.add_edge(('D', 'I'), 36)
GRAPH4.add_edge(('E', 'F'), 12)
GRAPH4.add_edge(('E', 'G'), 37)
GRAPH4.add_edge(('E', 'H'), 38)
GRAPH4.add_edge(('E', 'I'), 39)
GRAPH4.add_edge(('F', 'G'), 40)
GRAPH4.add_edge(('F', 'H'), 41)
GRAPH4.add_edge(('F', 'I'), 42)
GRAPH4.add_edge(('G', 'H'), 43)
GRAPH4.add_edge(('G', 'I'), 44)
GRAPH4.add_edge(('H', 'I'), 45)

print(GRAPH.get_verticies())
print(GRAPH.get_edges())
print()

def tsp(graph):
    print(evolutionary3(graph))
    print(end='')


if __name__ == "__main__":
    tsp(GRAPH2)
